### ISSUE TITLE
regression with bitflags 2.4

### ISSUE THREAD

**Issue by crobinso** [coconut-svsm/svsm#90] opened 2023-09-10 19:15 UTC
Trying to boot coconut-svsm git main (3c23e268aefc) throws a KVM error:

```
+ sudo /usr/bin/qemu-kvm -enable-kvm -cpu EPYC-v4 -machine q35,confidential-guest-support=sev0,memory-backend=ram1,kvm-type=protected -object memory-backend-memfd-private,id=ram1,size=8G,share=true -object sev-snp-guest,id=sev0,cbitpos=51,reduced-phys-bits=1,svsm=on -smp 8 -no-reboot -drive if=pflash,format=raw,unit=0,file=/usr/share/edk2/ovmf-coconutsvsm/OVMF_CODE.coconutsvsm.fd,readonly=on -drive if=pflash,format=raw,unit=1,file=/usr/share/edk2/ovmf-coconutsvsm/OVMF_VARS.coconutsvsm.fd,snapshot=on -drive if=pflash,format=raw,unit=2,file=./src/coconut-svsm/svsm.bin,readonly=on -netdev user,id=vmnic -device e1000,netdev=vmnic,romfile= -drive file=crobinso-snp.qcow2,if=none,id=disk0,snapshot=off -device virtio-scsi-pci,id=scsi0,disable-legacy=on,iommu_platform=on -device scsi-hd,drive=disk0,bootindex=0 -nographic
[sudo] password for crobinso: 
qemu-kvm: warning: Setting vm_type: protected
qemu-kvm: warning: Setting vm_type: protected
qemu-kvm: warning: UPM mode enabled, discard=(null)
qemu-kvm: warning: creating ROM device with private memory.
qemu-kvm: warning: creating ROM device with private memory.
qemu-kvm: warning: creating ROM device with private memory.
Flash mapping at 0xffc84000 size: 0x37c000
Flash mapping at 0xffb3f000 size: 0xc1000
[Stage2] COCONUT Secure Virtual Machine Service Module (SVSM) Stage 2 Loader
[Stage2] Order-00: total pages:    12 free pages:     0
[Stage2] Order-01: total pages:     1 free pages:     0
[Stage2] Order-02: total pages:     1 free pages:     1
[Stage2] Order-03: total pages:     1 free pages:     1
[Stage2] Order-04: total pages:     1 free pages:     1
[Stage2] Order-05: total pages:     1 free pages:     1
[Stage2] Total memory: 296KiB free memory: 240KiB
[Stage2]   kernel_region_phys_start = 0x0000008000000000
[Stage2]   kernel_region_phys_end   = 0x0000008010000000
[Stage2]   kernel_virtual_base   = 0xffffff8000000000
error: kvm run failed Invalid argument
EAX=0000000a EBX=00000000 ECX=00000000 EDX=00000000
ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
EIP=00000000 EFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 00000000 00000000 00000000
CS =0000 00000000 00000000 00000000
SS =0000 00000000 00000000 00000000
DS =0000 00000000 00000000 00000000
FS =0000 00000000 00000000 00000000
GS =0000 00000000 00000000 00000000
LDT=0000 00000000 00000000 00000000
TR =0000 00000000 00000000 00000000
GDT=     00000000 00000000
IDT=     00000000 00000000
CR0=80010011 CR2=00000000 CR3=00000000 CR4=000000f0
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000900
Code=<??> ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
```

Bisecting flagged the bitflags dep update. If I pin bitflags to `=2.3` and rebuild, things start working for me. diff:

```
diff --git a/Cargo.toml b/Cargo.toml
index a56e96b..57eeac7 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -18,7 +18,7 @@ test = true
 doctest = false
 
 [dependencies]
-bitflags = "2.4"
+bitflags = "=2.3"
 gdbstub = { version = "0.6.6", default-features = false, optional = true }
 gdbstub_arch = { version = "0.2.4", optional = true }
 log = { version = "0.4.17", features = ["max_level_info", "release_max_level_info"] }
```

But, uh, I'm not certain this isn't something funky with my setup, I was just swapping around distro rust vs rustup rust so who knows.

Anyone else seeing similar? CC @stefano-garzarella

**Comment by crobinso** [comment] 2023-09-10 20:39
FWIW I bisected the bitflags issue to https://github.com/bitflags/bitflags/commit/945c13f3013e50254bd4716a1c233a8d2682f37a . But nothing simple jumped out at me

**Comment by stefano-garzarella** [comment] 2023-09-11 11:38
@crobinso I tested the build after updating bitflags dependency, and it worked here on `AMD EPYC 7313`.
I also tested current SVSM main and I can't see the issue.

Then I tried to run `cargo update` and I saw the same issue.
```bash
$ cargo update
    Updating crates.io index
    Updating git repository `https://github.com/coconut-svsm/packit`
    Updating log v0.4.19 -> v0.4.20
    Updating num-traits v0.2.15 -> v0.2.16
    Updating paste v1.0.13 -> v1.0.14
    Updating proc-macro2 v1.0.63 -> v1.0.66
    Updating quote v1.0.29 -> v1.0.33
    Updating syn v1.0.109 -> v2.0.32
    Updating unicode-ident v1.0.10 -> v1.0.11
    Updating zerocopy v0.6.1 -> v0.6.4
    Updating zerocopy-derive v0.3.2 -> v0.6.4

...

[Stage2] COCONUT Secure Virtual Machine Service Module (SVSM) Stage 2 Loader
[Stage2] Order-00: total pages:    13 free pages:     1
[Stage2] Order-01: total pages:     2 free pages:     1
[Stage2] Order-02: total pages:     0 free pages:     0
[Stage2] Order-03: total pages:     1 free pages:     1
[Stage2] Order-04: total pages:     2 free pages:     2
[Stage2] Order-05: total pages:     0 free pages:     0
[Stage2] Total memory: 228KiB free memory: 172KiB
[Stage2]   kernel_region_phys_start = 0x0000008000000000
[Stage2]   kernel_region_phys_end   = 0x0000008010000000
[Stage2]   kernel_virtual_base   = 0xffffff8000000000
error: kvm run failed Invalid argument
EAX=0000000a EBX=00000000 ECX=00000000 EDX=00000000
ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
EIP=00000000 EFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 00000000 00000000 00000000
CS =0000 00000000 00000000 00000000
SS =0000 00000000 00000000 00000000
DS =0000 00000000 00000000 00000000
FS =0000 00000000 00000000 00000000
GS =0000 00000000 00000000 00000000
LDT=0000 00000000 00000000 00000000
TR =0000 00000000 00000000 00000000
GDT=     00000000 00000000
IDT=     00000000 00000000
CR0=80010011 CR2=00000000 CR3=00000000 CR4=000000f0
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000900
Code=<??> ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
```

Restoring `Cargo.lock` and rebuilding again fixed the issue, so I tried to update one crate per time and in my case it happens when updating `log`:
```
$ cargo update -p log                                                 
    Updating crates.io index
    Updating log v0.4.19 -> v0.4.20
```

Just to understand better, are you using the Cargo.lock in the repo or are you updating it?

**Comment by crobinso** [comment] 2023-09-11 13:46
No, I'm not using `cargo update`. So issue reproduces with untouched main branch, `git clean -xdf && make`. Then run `git clean -xdf`, update Cargo.toml with `=2.3` like above, `make` will reproduce the issue. Full diff after running `make` is:

```diff
diff --git a/Cargo.lock b/Cargo.lock
index 935a6cc..cc8a291 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -16,9 +16,9 @@ checksum = "bef38d45163c2f1dde094a7dfd33ccf595c92905c8f8f4fdc18d06fb1037718a"
 
 [[package]]
 name = "bitflags"
-version = "2.4.0"
+version = "2.3.3"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "b4682ae6287fcf752ecaabbfcc7b6f9b72aa33933dc23a554d853aea8eea8635"
+checksum = "630be753d4e58660abd17930c71b647fe46c27ea6b63cc59e1e3851406972e42"
 
 [[package]]
 name = "byteorder"
@@ -113,7 +113,7 @@ dependencies = [
 name = "svsm"
 version = "0.1.0"
 dependencies = [
- "bitflags 2.4.0",
+ "bitflags 2.3.3",
  "gdbstub",
  "gdbstub_arch",
  "log",
diff --git a/Cargo.toml b/Cargo.toml
index a56e96b..57eeac7 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -18,7 +18,7 @@ test = true
 doctest = false
 
 [dependencies]
-bitflags = "2.4"
+bitflags = "=2.3"
 gdbstub = { version = "0.6.6", default-features = false, optional = true }
 gdbstub_arch = { version = "0.2.4", optional = true }
 log = { version = "0.4.17", features = ["max_level_info", "release_max_level_info"] }
```

**Comment by stefano-garzarella** [comment] 2023-09-11 14:09
@crobinso wow, this is really confusing...

Could this strange behavior related in some way to the new target we are using?
CCing @00xc

I'll try to reproduce using the custom target we used before.

**Comment by joergroedel** [comment] 2023-09-11 14:25
I can also reproduce the issue with 'rustc 1.72.0 (5680fa18f 2023-08-23)'

**Comment by stefano-garzarella** [comment] 2023-09-11 14:46
@crobinso okay, I was doing my tests (wrongly)  with my `bitflags` branch. Now using `main` (commit 3c23e268aefcfff175253a9f8f6ccfa0c15a6e45) I have the same behavior as you.

Bisection here arrived at:
```
987dc2437c7bb390691be8b8d527e6c7530fa0f1 is the first bad commit
commit 987dc2437c7bb390691be8b8d527e6c7530fa0f1
Merge: dd2d701 dbbd717
Author: Jörg Rödel <jroedel@suse.de>
Date:   Thu Aug 31 11:06:00 2023 +0200

    Merge pull request #81 from 00xc/build/stablerust
    
    build: use stable Rust toolchain
```

And it might make more sense that it's something different that we introduced with the new target. I'm trying to investigate, but if I checkout commit dd2d701109a475f901c07cadbac95c9905df5b32 (just before changing the target and after introducing bitflags v2) it seems to work even if I update the crates.

**Comment by joergroedel** [comment] 2023-09-11 14:51
It crashes in the ELF loader, my guess is that the KernelLaunchInfo passed to svsm_start() is messed up somehow.

**Comment by joergroedel** [comment] 2023-09-11 14:55
And I can not reproduce in release builds.

**Comment by joergroedel** [comment] 2023-09-11 15:11
Found it, turns out the 8k boot stack is not enough anymore. I added some instrumentation to check maximum boot stack usage and got:

`[SVSM] Maximum boot stack usage: 9608 bytes`

So the right fix is increasing the boot stack size.

**Comment by stefano-garzarella** [comment] 2023-09-11 15:19
@joergroedel great! Just for learning, can you share the instrumentation that you add?

**Comment by joergroedel** [comment] 2023-09-11 15:28
Sure, here is the diff I used:

```diff
diff --git a/src/svsm.rs b/src/svsm.rs
index dc040a43c951..e3eb6f919a88 100644
--- a/src/svsm.rs
+++ b/src/svsm.rs
@@ -55,6 +55,7 @@ use core::ptr;

 extern "C" {
     pub static mut SECRETS_PAGE: SecretsPage;
+    pub static bsp_stack: u8;
     pub static bsp_stack_end: u8;
 }

@@ -83,11 +84,11 @@ global_asm!(
         movq    %r9, %rsi
         jmp svsm_start

-        .bss
+        .data

         .align 4096
     bsp_stack:
-        .fill 4*4096, 1, 0
+        .fill 4*4096, 1, 0xd0
     bsp_stack_end:

         .align 4096
@@ -293,10 +294,28 @@ static mut CONSOLE_SERIAL: SerialPort = SerialPort {
     port: SERIAL_PORT,
 };

+unsafe fn check_bsp_stack_usage() {
+    let bsp_stack_ptr = &bsp_stack as *const u8;
+    let vstart = VirtAddr::from(bsp_stack_ptr);
+    let vend = VirtAddr::from(&bsp_stack_end as *const u8);
+    let size = vend - vstart;
+    let boot_stack = slice::from_raw_parts(bsp_stack_ptr, size);
+    let mut left: usize = 0;
+
+    loop {
+        if boot_stack[left] != 0xd0 {
+            break;
+        }
+        left += 1;
+    }
+    log::info!("Maximum boot stack usage: {}", size - left);
+}
+
 pub fn boot_stack_info() {
     unsafe {
         let vaddr = VirtAddr::from(&bsp_stack_end as *const u8);
         log::info!("Boot stack starts        @ {:#018x}", vaddr);
+        check_bsp_stack_usage();
     }
 }


```

**Comment by joergroedel** [comment] 2023-09-12 08:58
Fixed now.

**Closed by joergroedel** 2023-09-12 08:58 UTC
